#ifndef SCENE_IDS_H
#define SCENE_IDS_H

enum SceneID
{
    MAIN_MENU_SCENE_ID = 0,
    SKIN_SELECTION_SCENE_ID,
    FACTION_SELECTION_SCENE_ID,
    SHOP_SCENE_ID,
    CASTLE_SCENE_ID,
    BATTLE_GROUNDS_SCENE_ID,
    WIN_SCENE_ID,
    LOSS_SCENE_ID
};

#endif
